/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Azaelmglw
 */
public class ViewVerificacionUsuario extends javax.swing.JPanel {

    /**
     * Creates new form ViewVerificacionUsuario
     */
    public ViewVerificacionUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_usuario = new javax.swing.JLabel();
        jlb_contraseña = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jpwd_contraseña = new javax.swing.JPasswordField();
        jbtn_iniciar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));

        jlb_usuario.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jlb_usuario.setForeground(new java.awt.Color(204, 204, 204));
        jlb_usuario.setText("Usuario:");

        jlb_contraseña.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jlb_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        jlb_contraseña.setText("Contraseña:");

        jtf_usuario.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jtf_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jpwd_contraseña.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jpwd_contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbtn_iniciar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_iniciar.setText("Iniciar");
        jbtn_iniciar.setMaximumSize(new java.awt.Dimension(360, 46));
        jbtn_iniciar.setMinimumSize(new java.awt.Dimension(360, 46));
        jbtn_iniciar.setPreferredSize(new java.awt.Dimension(360, 46));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_usuario)
                            .addComponent(jlb_contraseña))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpwd_contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_usuario)
                    .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_contraseña)
                    .addComponent(jpwd_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jbtn_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_iniciar;
    public javax.swing.JLabel jlb_contraseña;
    public javax.swing.JLabel jlb_usuario;
    public javax.swing.JPasswordField jpwd_contraseña;
    public javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
